#Modules are loaded in the order they are listed here.
enabled_modules:
- modules.DANPrompt
- modules.DaisyPrompt
- modules.Daisy.Daisy
- modules.SetLocation
- modules.WeatherNoaaNl.WeatherNoaaNl
- modules.TTSGoogle
- modules.Calculator
- modules.DiskFree
- modules.Memories

conversation_id: 123
#Set the id of an existing conversation to load it.
#Leave empty to load the latest conversation.
#Set the id of a non-existing conversation to create a new one with that ID.

#API Keys for the modules that need them.
keys:
  assembly_ai: 500da1c2e7b3427194cd5005546ed532
  openai: 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
  serp_api: 5e756ef2ca38768c0c0db17264194600abd0050ee868b6e73fc5bbbd16de9ab8
  elevenlabs: 8dff1466712e295ccbbabf4068b62182
  porcupine: QTQ28lQFSW2Fdw+FvEtFcTDkRz7+jJepnQ1Bmm+oB164gmfJJlO34A==

#Set natural language location. Currently only used for weather.

hardware:
  input_device_index: 1
  led: false

print_text: true
log_level: WARNING

TTS:
  speed: 1.1

TTSElevenLabs:
  voice: Daisy

TTSGoogleCloud:
  voice: en-US-Studio-O
  project: sonorous-veld-383603

#Set natural language location.
location: 2825 Knox Ct, Saint Louis, Missouri, 63139
#Set latlon to bypass geocoding (sometimes the service is not available).
latlon: 38.610374982753,-90.29175699236418
